apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-api.fullname" . }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
    {{- include "demo-api.tenantLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      # Named port is referenced by the ServiceMonitor.
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "demo-api.selectorLabels" . | nindent 4 }}
